[build]
 cmd = "go build -o main cmd/main.go"
 bin = "main"
 dir = "."
 include_ext = ["go"]
 exclude_dir = ["vendor"]
 run_after_build = "chmod -x main"


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  level = "debug"
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
